#!/bin/ksh
#set -x
srcdir=`pwd`
ext="131021b"
library=SCRIP
casename=`basename $srcdir`
n_p_t=1_4_1
for SRC_GRID in bggd icos ssea ; do
   TGT_GRID=nogt
   for remap in distwgt conserv1st ; do
       ./run_regrid.sh $SRC_GRID $TGT_GRID $remap $n_p_t $library $ext
   done
done
for SRC_GRID in bggd ssea ; do
   TGT_GRID=nogt
   for remap in bili bicu ; do
        ./run_regrid.sh $SRC_GRID $TGT_GRID $remap $n_p_t $library $ext
   done
done 
SRC_GRID=bggd
TGT_GRID=nogt
remap=conserv2nd
./run_regrid.sh $SRC_GRID $TGT_GRID $remap $n_p_t $library $ext
#
for TGT_GRID in bggd icos ssea ; do
   SRC_GRID=nogt
   for remap in distwgt bili bicu conserv1st conserv2nd ; do
        ./run_regrid.sh $SRC_GRID $TGT_GRID $remap $n_p_t $library $ext
   done
done
