#!/bin/ksh
#set -x
srcdir=`pwd`
n_p_t=$1
ext=$2
fana=sinusoid
library=ESMF
casename=`basename $srcdir`
remaps="distwgt bili bicu conserv_1st_fracarea conserv_2nd_fracarea"

for SGRID in bggd icos sse7  ; do
   for TGRID in nogt torc ; do
       for remap in $remaps ; do
	   echo "$SGRID $TGRID $remap $n_p_t $library $ext"
	   ./run_regrid.sh $SGRID $TGRID $remap $fana $n_p_t $library $ext
       done
   done
done

for TGRID in bggd icos sse7  ; do
    for SGRID in nogt torc ; do
	echo "$SGRID $TGRID $remap $n_p_t $library $ext"
	for remap in $remaps ; do
	    ./run_regrid.sh $SGRID $TGRID $remap $fana $n_p_t $library $ext
	done
    done
done
