#!/bin/ksh
#set -x
srcdir=`pwd`
n_p_t=$1
library=$2
ext=$3
casename=`basename $srcdir`
fileres=$srcdir/RUNDIR_${library}_${ext}/resu_${n_p_t}_${library}.txt
echo $n_p_t > $fileres
for SRC_GRID in bggd icos ssea ; do
   TGT_GRID=nogt
   for remap in distwgt conserv1st ; do
       rundir=$srcdir/RUNDIR_${library}_${ext}/${casename}_${SRC_GRID}_${TGT_GRID}_${remap}_${n_p_t}_${library}_${ext}
       resu=`grep "Error mean" ${rundir}/model1.out_100 | awk -F " " '{print $12}'`
       echo ${SRC_GRID}' '${TGT_GRID}' '${remap}'  : '${resu} >> $fileres
   done
done
for SRC_GRID in bggd ssea ; do
   TGT_GRID=nogt
   for remap in bili bicu ; do
	rundir=$srcdir/RUNDIR_${library}_${ext}/${casename}_${SRC_GRID}_${TGT_GRID}_${remap}_${n_p_t}_${library}_${ext}
        resu=`grep "Error mean" ${rundir}/model1.out_100 | awk -F " " '{print $12}'`
        echo ${SRC_GRID}' '${TGT_GRID}' '${remap}'  : '${resu} >> $fileres
   done
done 
SRC_GRID=bggd
TGT_GRID=nogt
remap=conserv2nd
rundir=$srcdir/RUNDIR_${library}_${ext}/${casename}_${SRC_GRID}_${TGT_GRID}_${remap}_${n_p_t}_${library}_${ext}
resu=`grep "Error mean" ${rundir}/model1.out_100 | awk -F " " '{print $12}'`
echo ${SRC_GRID}' '${TGT_GRID}' '${remap}'  : '${resu} >> $fileres
#
for TGT_GRID in bggd icos ssea ; do
   SRC_GRID=nogt
   for remap in distwgt bili bicu conserv1st conserv2nd ; do
        rundir=$srcdir/RUNDIR_${library}_${ext}/${casename}_${SRC_GRID}_${TGT_GRID}_${remap}_${n_p_t}_${library}_${ext}
        resu=`grep "Error mean" ${rundir}/model1.out_100 | awk -F " " '{print $12}'`
        echo ${SRC_GRID}' '${TGT_GRID}' '${remap}' : '${resu} >> $fileres
   done
done
echo 'Differences'
echo `diff $srcdir/resu_${library}.txt_OK $fileres`
