#!/bin/ksh
#set -x
srcdir=`pwd`
n_p_t=$1
ext=$2
library=ESMF
casename=`basename $srcdir`
for SGRID in bggd icos sse7  ; do
   for TGRID in nogt torc ; do
       for remap in distwgt bili bicu conserv1st conserv2nd ; do
	   echo "$SGRID $TGRID $remap $n_p_t $library $ext"
	   ./run_regrid.sh $SGRID $TGRID $remap $n_p_t $library $ext
       done
   done
done

for TGRID in bggd icos sse7  ; do
    for SGRID in nogt torc ; do
	echo "$SGRID $TGRID $remap $n_p_t $library $ext"
	for remap in distwgt bili bicu conserv1st conserv2nd ; do
	    ./run_regrid.sh $SGRID $TGRID $remap $n_p_t $library $ext
	done
    done
done
