#!/bin/ksh
#set -x
srcdir=`pwd`
fana=$1
n_p_t=$2
ext=$3
library=XIOS
casename=`basename $srcdir`
remaps="conserv_1st_fracarea conserv_2nd_fracarea"

for SGRID in bggd icos sse7  ; do
    for TGRID in nogt torc ; do
	for remap in $remaps ; do
	    echo "$SGRID $TGRID $remap $n_p_t $library $ext"
	    ./run_regrid.sh $SGRID $TGRID $remap $fana $n_p_t $library $ext
	done
    done
done

for TGRID in bggd icos sse7  ; do
    for SGRID in nogt torc ; do
	echo "$SGRID $TGRID $remap $n_p_t $library $ext"
	for remap in $remaps ; do
	    ./run_regrid.sh $SGRID $TGRID $remap $fana $n_p_t $library $ext
	done
    done
done
