name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    uses: access-nri/workflows/.github/workflows/oasis3-mct-build.yml@main

    permissions:
      packages: read
