name: Build image

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    uses: access-nri/workflows/.github/workflows/build-and-push-image.yml@main
    with:
      container-registry: ghcr.io
      container-path: access-nri/${{ github.event.repository.name }}-build-image
      dockerfile-directory: ci
    permissions:
      contents: read
      packages: write
