name: Build image

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    uses: access-nri/workflows/.github/workflows/oasis3-mct-build-and-push-image.yml@main

    permissions:
      contents: read
      packages: write
