name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    uses: access-nri/workflows/.github/workflows/build-package.yml@main
    with:
      container-registry: ghcr.io
      container-name: ${{ github.event.repository.name }}-build-image
      package-name: access.nri.oasis3-mct
    permissions:
      packages: read
