name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/access-nri/oasis3-mct-build-image:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Build oasis3-mct via spack
      run: spack -v install --only package access.nri.oasis3-mct
